/* CONSULTAS
SELECT * FROM `PRODUCTOS` WHERE 1
SELECT SECCIÓN,NOMBREARTÍCULO, PRECIO FROM `PRODUCTOS` WHERE SECCIÓN="CERÁMICA" OR SECCIÓN="DEPORTES"
SELECT * FROM PRODUCTOS WHERE SECCIÓN="DEPORTES" AND PAÍSDEORIGEN="USA" 
SELECT * FROM PRODUCTOS WHERE FECHA BETWEEN "2000-03-01" AND "2000-04-30"
SELECT SECCIÓN,NOMBREARTÍCULO, PRECIO FROM `PRODUCTOS` WHERE SECCIÓN="CERÁMICA" OR SECCIÓN="DEPORTES" ORDER BY SECCIÓN
SELECT SECCIÓN,NOMBREARTÍCULO, PRECIO FROM `PRODUCTOS` WHERE SECCIÓN="CERÁMICA" OR SECCIÓN="DEPORTES" ORDER BY `PRECIO` DESC
SELECT SECCIÓN,NOMBREARTÍCULO, PRECIO FROM `PRODUCTOS` WHERE SECCIÓN="CERÁMICA" OR SECCIÓN="DEPORTES" ORDER BY `SECCIÓN`,`PRECIO` DESC
SELECT SECCIÓN,SUM(PRECIO) FROM PRODUCTOS GROUP BY SECCIÓN 
SELECT SECCIÓN,SUM(PRECIO) FROM PRODUCTOS GROUP BY SECCIÓN ORDER BY SUM(PRECIO)
SELECT SECCIÓN,SUM(PRECIO)AS SUMA_P FROM PRODUCTOS GROUP BY SECCIÓN ORDER BY SUMA_P 
SELECT SECCIÓN, NOMBREARTÍCULO ,SUM(PRECIO)AS SUMA_P FROM PRODUCTOS GROUP BY SECCIÓN ORDER BY SUMA_P 
SELECT SECCIÓN, AVG(PRECIO)AS MEDIA_P FROM PRODUCTOS GROUP BY SECCIÓN HAVING SECCIÓN="DEPORTES" OR SECCIÓN="CERAMICA"
SELECT SECCIÓN, AVG(PRECIO)AS MEDIA_P FROM PRODUCTOS GROUP BY SECCIÓN HAVING SECCIÓN="DEPORTES" OR SECCIÓN="CERAMICA" ORDER BY SECCIÓN DESC
SELECT SECCIÓN, MAX(PRECIO) AS PRECIO_MAXI FROM PRODUCTOS WHERE SECCIÓN="CONFECCIÓN" GROUP BY SECCIÓN
SELECT SECCIÓN, NOMBREARTÍCULO ,MAX(PRECIO) AS PRECIO_MAXI FROM PRODUCTOS WHERE SECCIÓN="CONFECCIÓN" GROUP BY SECCIÓN
SALE EL PRIMER ARTICULO Y DE LA SECCION NOMBREARTICULO Y NO EL NOMBRE DEL QUE TIENE EL MAX PRECIO
UPDATE PRODUCTOS SET PRECIO=PRECIO+10 WHERE SECCIÓN="DEPORTES"
UPDATE PRODUCTOS SET PRECIO=PRECIO-10 WHERE SECCIÓN="DEPORTES"
NO EXISTE DESHACER
DELETE FROM PRODUCTOS WHERE SECCIÓN="DEPORTIVOS" AND PRECIÓ BETWEEN 50 AND 100
SELECT CÓDIGOARTÍCULO,NOMBREARTÍCULO,PRECIO,ROUND(PRECIO*(PRECIO*0.21),2) AS IVA FROM PRODUCTOS
SELECT NOMBREARTÍCULO,FECHA, NOW() AS DIA_HOY, DATEDIFF(NOW(),FECHA) AS DIFERENCIA FROM PRODUCTOS WHERE SECCIÓN="DEPORTES"
SELECT NOMBREARTÍCULO,FECHA, DATE_FORMAT(NOW(),"%D-%M") AS NUEVO_FORMATO FROM PRODUCTOS WHERE SECCIÓN="DEPORTES"
SELECT * FROM PRODUCTOS WHERE SECCIÓN="DEPORTES" UNION SELECT* FROM ProductosNuevos
SALE 1 VEZ
SELECT * FROM PRODUCTOS WHERE SECCIÓN="DEPORTES" UNION ALL SELECT* FROM ProductosNuevos
MODIFICAR TABLAS VIDEO12
UPDATE PRODUCTOS SET SECCIÓN="DEPORTIVOS" WHERE SECCIÓN="DEPORTES"
UPDATE PRODUCTOS SET SECCIÓN="DEPORTIVOS" WHERE SECCIÓN="DEPORTES"
SELECT * FROM CLIENTES INNER JOIN PEDIDOS ON CLIENTES.[CODIGOCLIENTE]=PEDIDOS.[CÓDIGOCLIENTE] WHERE POBLACION="MADRID"
*/
SELECT * FROM `CLIENTES` WHERE 1
SELECT `POBLACIÓN`, COUNT(`CÓDIGOCLIENTE`) AS N_CLIENTE FROM CLIENTES GROUP BY `POBLACIÓN`
CREATE TABLE CLIENTES_MADRID SELECT * FROM CLIENTES WHERE POBLACIÓN="MADRID"
DELETE FROM CLIENTES WHERE POBLACIÓN="MADRID"
